global:
  scrape_interval: 5s
  external_labels:
    monitor: 'Monitoring'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['172.31.10.6:9090'] #edit
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['172.31.10.10:9100', '172.31.10.6:9100'] #edit
  - job_name: 'cAdvisor' 
    static_configs:
      - targets: ['172.31.10.10:8080', '172.31.10.6:8080'] #edit
  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['172.31.10.10:9113'] #edit