global:
  scrape_interval: 5s
  external_labels:
    monitor: 'Monitoring'
scrape_configs:
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['192.168.9.102:9100'] #edit
  - job_name: 'cAdvisor' 
    static_configs:
      - targets: ['192.168.9.102:8080'] #edit
  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['192.168.9.102:9113'] #edit